import './globals.css';
import { ReactNode } from 'react';
import Cabecalho from '../components/Cabecalho/Cabecalho';
import Rodape from '../components/Rodape/Rodape';

export const metadata = {
  title: 'Student Portfolio',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className="flex flex-col min-h-screen"> 
        <Cabecalho />
        <main className="container mx-auto p-6 flex-grow">{children}</main>
        <Rodape />
      </body>
    </html>
  );
}
